# script to generate `data/hampi.rda` 

```{r load, echo = FALSE}
library (magrittr)
library (osmdata)
```
```{r}
hampi <- opq ("hampi india") %>%
    add_osm_feature (key = "highway") %>%
    osmdata_sf () %>%
    osm_poly2line () %>%
    extract2 ("osm_lines")
```
Then need to get rid of columns, especially the ones with Kannada names which
are non-UTF8
```{r}
nms <- c ("osm_id", "bicycle", "covered", "foot", "highway", "incline",
          "motorcar", "motorcycle", "motor_vehicle", "oneway", "surface",
          "tracktype", "tunnel", "width", "geometry")
hampi <- hampi [, match (nms, names (hampi))]
```
```{r}
devtools::use_data (hampi, overwrite = TRUE, compress = 'xz')
```

# generate `data/weight_profiles`

```{r}
library (magrittr)
theurl <- "https://www.routino.org/xml/routino-profiles.xml"
#dat <- rvest::html (theurl)
dat <- rvest::html (theurl) %>%
    rvest::html_nodes("profile") %>%
    xml2::as_list ()
```
```{r}
weighting_profiles <- lapply (dat, function (i) {
                 di <- i$preferences
                 res <- lapply (di, function (j) 
                         c (attr (i, "name"),
                            attr (j, "highway"),
                            attr (j, "percent")))
                 do.call (rbind, res)
          })
# Then add living_street, bridleway, and footway to all profiles
# https://wiki.openstreetmap.org/wiki/Tag:highway%3Dliving_street
nms <- sapply (weighting_profiles, function (i) i [1, 1])
#               living_street   footway     bridleway
# "foot"        95              100         100
# "horse"       80              100         100
# "wheelchair"  95              100         50
# "bicycle"     95              90          70
# "moped"       60              0           0
# "motorcycle"  50              0           0
# "motorcar"    40              0           0
# "goods"       30              0           0
# "hgv"         30              0           0
# "psv"         30              0           0
wt_ls <- c (95, 80, 95, 95, 60, 50, 40, 30, 30, 30) # living street
wt_br <- c (100, 100, 50, 70, 0, 0, 0, 0, 0, 0) # bridleway
wt_fw <- c (100, 100, 100, 90, 0, 0, 0, 0, 0, 0) # bridleway
names (wt_ls) <- names (wt_br) <- names (wt_fw) <- nms
weighting_profiles <- lapply (seq (weighting_profiles), function (i)
                              {
                                  wi <- weighting_profiles [[i]]
                                  nmi <- wi [1, 1]
                                  wti <- wt_ls [which (nms == nmi)]
                                  wi <- rbind (wi, c (nmi, 
                                                      "living_street",
                                                      wti))
                                  wtb <- wt_br [which (nms == nmi)]
                                  wi <- rbind (wi, c (nmi, 
                                                      "bridleway",
                                                      wtb))
                                  wtf <- wt_fw [which (nms == nmi)]
                                  wi <- rbind (wi, c (nmi, 
                                                      "footway",
                                                      wtf))

                                  rownames (wi) <- rep ("preference", nrow (wi))
                                  return (wi)
                              })

weighting_profiles <- do.call (rbind, weighting_profiles)
weighting_profiles <- data.frame (name = weighting_profiles [, 1],
                           way = weighting_profiles [, 2],
                           value = as.numeric (weighting_profiles [, 3]),
                           stringsAsFactors = FALSE)

# Then add waiting times at traffic lights in seconds, with value of 48s taken from
# http://dx.doi.org/10.1016/j.trb.2013.02.002
# see also National Assoc. City Transportation Officials guidelines:
# https://nacto.org/publication/urban-street-design-guide/intersection-design-elements/traffic-signals/signal-cycle-lengths/
# recommended "Short cycle length" of 60-90 secons
wait_time <- 48
nms <- paste0 ("lights_", unique (weighting_profiles$name))
lights <- data.frame ("name" = nms,
                      "way" = rep ("traffic_lights",
                                   length (nms)),
                      "value" = rep (wait_time, length (names)),
                      stringsAsFactors = FALSE)
weighting_profiles <- rbind (weighting_profiles, lights)

# change percentage value to 0-1
index <- which (!grepl ("lights_", weighting_profiles$name))
weighting_profiles$value [index] <- weighting_profiles$value [index] / 100
usethis::use_data (weighting_profiles, overwrite = TRUE, compress = 'xz')
```
