// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcpp_get_sp
Rcpp::NumericMatrix rcpp_get_sp(Rcpp::DataFrame graph, std::string heap_type);
RcppExport SEXP _pqspr_rcpp_get_sp(SEXP graphSEXP, SEXP heap_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type graph(graphSEXP);
    Rcpp::traits::input_parameter< std::string >::type heap_type(heap_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_get_sp(graph, heap_type));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_get_sp_radix
Rcpp::NumericMatrix rcpp_get_sp_radix(Rcpp::DataFrame graph);
RcppExport SEXP _pqspr_rcpp_get_sp_radix(SEXP graphSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type graph(graphSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_get_sp_radix(graph));
    return rcpp_result_gen;
END_RCPP
}
