# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' rcpp_get_sp
#'
#' @noRd
rcpp_get_sp <- function(graph, quiet) {
    .Call(`_pqspr_rcpp_get_sp`, graph, quiet)
}

