# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' rcpp_sample_graph
#'
#' Randomly sample one connected componnent of a graph
#'
#' @param graph graph to be processed
#' @param nverts_to_sample Number of vertices to sample
#' @param e0 Random edge of graph from which to get first vertex to include in
#' sample
#' @param is_spatial Is the graph spatial or not?
#' @param quiet If TRUE, display progress
#'
#' @return Smaller sub-set of \code{graph}
#'
#' @noRd
rcpp_sample_graph <- function(graph, nverts_to_sample, e0, is_spatial) {
    .Call(`_dodgr_rcpp_sample_graph`, graph, nverts_to_sample, e0, is_spatial)
}

#' rcpp_get_components
#'
#' Get component numbers for each edge of graph
#'
#' @param graph graph to be processed
#' @param is_spatial Is the graph spatial or not?
#'
#' @return Vector of component numbers, one for each edge.
#'
#' @noRd
rcpp_get_components <- function(graph) {
    .Call(`_dodgr_rcpp_get_components`, graph)
}

#' rcpp_make_compact_graph
#'
#' Removes nodes and edges from a graph that are not needed for routing
#'
#' @param graph graph to be processed
#' @param is_spatial Is the graph spatial or not?
#' @param quiet If TRUE, display progress
#'
#' @return \code{Rcpp::List} containing one \code{data.frame} with the compact
#' graph, one \code{data.frame} with the original graph and one
#' \code{data.frame} containing information about the relating edge ids of the
#' original and compact graph.
#'
#' @noRd
rcpp_make_compact_graph <- function(graph, is_spatial, quiet) {
    .Call(`_dodgr_rcpp_make_compact_graph`, graph, is_spatial, quiet)
}

#' rcpp_insert_vertices
#'
#' Insert routing vertices in compact graph
#'
#' @param fullgraph graph to be processed
#' @param compactgraph graph to be processed
#' @param pts_to_insert Index into graph of those points closest to desired
#' routing points. These are to be kept in the compact graph.
#' @return \code{Rcpp::List} containing one \code{data.frame} with the compact
#' graph, one \code{data.frame} with the original graph and one
#' \code{data.frame} containing information about the relating edge ids of the
#' original and compact graph.
#'
#' @noRd
rcpp_insert_vertices <- function(fullgraph, compactgraph, pts_to_insert, is_spatial) {
    .Call(`_dodgr_rcpp_insert_vertices`, fullgraph, compactgraph, pts_to_insert, is_spatial)
}

#' rcpp_get_sp
#'
#' @noRd
rcpp_get_sp <- function(graph, vert_map_in, fromi, toi, heap_type) {
    .Call(`_dodgr_rcpp_get_sp`, graph, vert_map_in, fromi, toi, heap_type)
}

#' rcpp_sf_as_network
#'
#' Return OSM data in Simple Features format
#'
#' @param sf_lines An sf collection of LINESTRING objects
#' @param pr Rcpp::DataFrame containing the weighting profile
#'
#' @return Rcpp::List objects of OSM data
#'
#' @noRd
rcpp_sf_as_network <- function(sf_lines, pr) {
    .Call(`_dodgr_rcpp_sf_as_network`, sf_lines, pr)
}

#' rcpp_points_index
#'
#' Get index of nearest vertices to list of points
#'
#' @param graph Rcpp::DataFrame containing the graph
#' @param pts Rcpp::DataFrame containing the routing points
#'
#' @return Rcpp::NumericVector index into graph of nearest points
#'
#' @noRd
rcpp_points_index <- function(xy, pts) {
    .Call(`_dodgr_rcpp_points_index`, xy, pts)
}

